name: "Deploy New Landing Zone"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      #ipamApiScope:
        #description: 'IPAM API Scope'
        #required: true
        #default: '' # Example: 'https://api.ipam.example/scope'
      ipamUrl:
        description: 'IPAM URL'
        required: true
        default: 'https://ipam-xxxx.azurewebsites.net/api/spaces/CorpSpace/blocks/CorpBlockWestEurope01/reservations'
      ipamSize:
        description: 'IPAM Size'
        required: false
        default: '24' # This will reserve the next available /24 address space from the Azure IPAM block in IPAM_URL

permissions:
  id-token: write
  contents: read


#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  IPAM_API_SCOPE : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSJ9.eyJhdWQiOiIxNzk2NzBmNy0zZDQxLTRlNjYtOTY5Mi0yZDUwZGVmZThlOTMiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vODMyYjA5MDgtMzU4NS00Mjk0LWEwMWMtNzc2M2ZjMTk1MDA2L3YyLjAiLCJpYXQiOjE3MTA3NzIyNDMsIm5iZiI6MTcxMDc3MjI0MywiZXhwIjoxNzEwNzc3NTcwLCJhaW8iOiJBWVFBZS84V0FBQUFla0pCTGxyNHB4TU5rc0RzeldEa0xzQ2lKZXBBaUE5NzhqUUk2NGNXTDljQmZjcGtRMm9DRlFycGJCZk94bU9JMVRRZzBGWUZ0UkxnVVc0RUtEUkhRVTdJbXBiRUFNME0yOEs1bkxpdGZ1Z2x4SEVNMHRZbFMwelpqMVU5Yk5ETEhCbldkYnNOdkVScVd2Ty96UEVZakZ2eitPV05jK0EzZ1daR0J2UDBOKzg9IiwiYXpwIjoiOWFiYzhlODMtN2I1OS00OThkLTk0YWQtZmM2MmNiOWYzM2UwIiwiYXpwYWNyIjoiMCIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzdlZDliZGM3LTk2NGQtNGRjMC05MDg0LTgxMmI5MGUwNWM2ZC8iLCJuYW1lIjoiUmFwaGFlbCBCb2F0ZW5nLUFtcG9uc2FoIiwib2lkIjoiMDY0MDMxNGQtZTAzNi00MWZlLTkzZTAtN2JiYWYxYTRkNTI2IiwicHJlZmVycmVkX3VzZXJuYW1lIjoicmFwaGFlbC5ib2F0ZW5nLWFtcG9uc2FoQGthaW5vcy5jb20iLCJyaCI6IjAuQVVzQUNBa3JnNFUxbEVLZ0hIZGpfQmxRQnZkd2xoZEJQV1pPbHBJdFVONy1qcE1aQVJRLiIsInNjcCI6ImFjY2Vzc19hc191c2VyIiwic3ViIjoiLV95QWZPU2RxbVhsRHFQMEEtbk80ZkNsdkMyQm16b1BOaFZGZWs1bzhmMCIsInRpZCI6IjgzMmIwOTA4LTM1ODUtNDI5NC1hMDFjLTc3NjNmYzE5NTAwNiIsInV0aSI6ImhoeFVBcV9DNzA2cVlfYk1ZdzRtQUEiLCJ2ZXIiOiIyLjAifQ.rjA755BI-_50qdDK7MVpG_SJiQJSjfoJfi3o58LRnGw4sxbtLKNGhE6GdbzuDuqyygPjdXY0rn-cYE1kwu4bwodhIUYfU2gV_PNgOVkpOMod1WaBYijf4-x-tu--nwYl22RPybrFBKcibSGbSU2p-wtgOG4L3f8UNeCHWW17an05tOB1sChr4CnI-_FwE9DntS7nyzT2dJNhYcdFNiDcVa6ZEY8TFfISMB3YdD2qt-e7C44lNkkrmkiIylj6MSwmH_ClqQDXybd8WUfsaSpVIZ2smeZx9a2sU8BnyzA_xk2FdsgQIW7DnaldbH5LCkdP85lXO4ETOPSn16N6kEgMRw"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  Deploy_New_LandingZone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OIDC Login To Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true


      - name: Get Available Address Space From IPAM
        id: getipam
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $scriptPath = "/home/runner/work/Ipam-vending/Ipam-vending/Pipeline-scripts/fetchAddressPrefix.ps1"
            $ipamApiScope = "${{ github.event.inputs.ipamApiScope }}"
            $ipamUrl = "${{ github.event.inputs.ipamUrl }}"
            $ipamSize = ${{ github.event.inputs.ipamSize }}
            Write-Host "Using IPAM API Scope: $ipamApiScope"
            Write-Host "Using IPAM URL: $ipamUrl"
            Write-Host "Requested IPAM Size: $ipamSize"
            & pwsh $scriptPath -IPAM_API_SCOPE "$ipamApiScope" -IPAM_URL "$ipamUrl" -IPAM_SIZE $ipamSize
          azPSVersion: "latest"


      - name: Setup Terraform (Pinned Version)
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.7.5" # Example version, adjust as needed

      - name: Initialize Terraform
        run: terraform init
        working-directory: /home/runner/work/Ipam-vending/Ipam-vending/Terraform

      - name: Create Terraform Execution Plan
        run: |
          terraform plan -out=tfplan \
            -var "vnet_tag=${{ steps.getipam.outputs.id }}" \
            -var "address_prefix=${{ steps.getipam.outputs.cidr }}"
        working-directory: /home/runner/work/Ipam-vending/Ipam-vending/Terraform

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan
        working-directory: /home/runner/work/Ipam-vending/Ipam-vending/Terraform

